language: scala
sudo: false
scala:
  - "2.13.3"
  - "2.12.12"
  - "2.11.12"
  - "2.10.7"
jdk:
  - openjdk8
script:
  - sbt ++${TRAVIS_SCALA_VERSION} test:compile checkScalariform
  - sbt ++${TRAVIS_SCALA_VERSION} test
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
  - scala: 0.26.0-RC1
    name: dotty
    jdk: openjdk8
    script:
    - sbt "++ 0.26.0-RC1!" test
